{
 "title": "Домашнее задание к занятию 14 «Средство визуализации Grafana»",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "количество места на файловой системе",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes" }
   ]
  },
  {
   "title": "Средняя нагрузка на процессор CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" },
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "Количество свободной оперативной памяти;",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "всего оперативной памяти" },
    {
     "expr": "node_memory_MemFree_bytes",
     "legendFormat": "количество свободной оперативной памяти;"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  }
 ]
}